name: Deploy Static Site

on:
  push:
    branches:
      - main  # Adjust as needed

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Adjust to match your Node.js version

      - name: Install dependencies
        run: npm install  # Adjust if you're using a different package manager

      - name: Build project
        run: npm run build  # Adjust to match your build command

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build  # Adjust to the directory containing your built files

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
